[[cells]]
name = "quantum-resistant-lock-script"
enable_type_id = true
location = { file = "../../build/release/c-sphincs-all-in-one-lock" }


# This is the lock script in output. Check it very carefully.
# 1. xxuejie@gmail.com       ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw8jqfpfe9lwsvs74j3a27aalhqshrslps8hlplq
# 2. quake.wang@gmail.com    ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2u7q5rqr3nam68g2wfel9365l855m7fcg58j52a
# 3. hanssen0@hanssen0.com   ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0m2fr3ygwszxa77l5r7utgku85wyqvjac5wppfj
# 4. rink1969@gmail.com      ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt4q36wdxa34k89g5snyw694jy0nxht8yshfyw55
# 5. copperheart05@gmail.com ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqf4wq9qpe3pk5c0cy0g40mymrf26cqg4qctwdqge

[lock]
code_hash = "0x36c971b8d41fbd94aabca77dc75e826729ac98447b46f91e00796155dddb0d29"
args = "0x6040e88e7d2b5f66c3adfe3777a94defb6d32fc3"
hash_type = "data1"
